[package]
name = "ilert"
version = "0.3.0"
authors = ["Christian Froehlingsdorf <chris@ilert.com>"]
edition = "2018"
description = "The official iLert api bindings."
keywords = ["ilert", "http", "api", "client", "rest"]
readme = "README.md"
license = "MIT"
homepage = "https://ilert.de"
documentation = "https://docs.rs/ilert"
repository = "https://github.com/iLert/ilert-rust"
categories = ["api-bindings"]

[dependencies]
reqwest = "0.9.22"
base64 = "0.11.0"
serde_json = "1.0.42"